#!/usr/bin/env python3
"""Build the site's two drawn marks (Oct 6 2026, the zen look). Zero dependencies.

    python scripts/build_zen_marks.py

Writes (generated: edit this script, never the SVGs):
  img/recursive-logo-seal.svg  recursive.eco's spiral, recoloured as a cinnabar seal. The spiral's
                               path is read unchanged from img/recursive-logo.svg (copied from
                               recursive-eco apps/landing/recursive-logo.svg); only its colour, line
                               weight and setting change: it is cut out of a seal-red block, the way
                               the lines of a hanko are.
  img/enso.svg                 one brush circle, thick where the brush lands and dry where it lifts.
                               Drawn here, not a reproduction. theme.css uses it as a CSS mask
                               (.enso), so its colour comes from the theme tokens.

The colours are theme.css's --seal (#9c3b2a) and --bg (#f3efe6); keep them in step.
"""
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEAL = "#9c3b2a"   # theme.css --seal
PAPER = "#f3efe6"  # theme.css --bg


def build_seal() -> str:
    src = (ROOT / "img/recursive-logo.svg").read_text(encoding="utf-8")
    d = re.search(r'<path d="([^"]+)"', src).group(1)
    # The speckle filter leaves a few pin-holes in the red, like a seal pressed by hand.
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="400" height="400" role="img" aria-label="recursive.eco">\n'
        '<!-- Generated by scripts/build_zen_marks.py. recursive.eco spiral, path unchanged, set as a cinnabar seal. -->\n'
        '<defs><filter id="pressed" x="0" y="0" width="100%" height="100%">'
        '<feTurbulence type="fractalNoise" baseFrequency=".3" numOctaves="4" seed="11" result="n"/>'
        '<feColorMatrix in="n" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 -14 10.9" result="speck"/>'
        '<feComposite in="SourceGraphic" in2="speck" operator="in"/>'
        '</filter></defs>\n'
        f'<rect x="4" y="4" width="92" height="92" rx="7" fill="{SEAL}" filter="url(#pressed)"/>\n'
        f'<path transform="translate(50 50) scale(.8) translate(-50 -50)" d="{d}" '
        f'stroke="{PAPER}" stroke-width="6" fill="none" stroke-linecap="round"/>\n'
        '</svg>\n'
    )


def build_enso() -> str:
    cx = cy = 50
    th0, sweep = math.radians(118), math.radians(326)

    def r_at(t):
        return 37 + 1.3 * math.sin(3 * math.pi * t + .6) + .5 * math.sin(9 * math.pi * t)

    def w_at(t):
        if t < .06:
            return 6.5 + 25 * t                       # the loaded brush lands
        if t < .75:
            return 8 - 2.6 * (t - .06) / .69 + .4 * math.sin(11 * t)
        return max(.4, 5.4 * (1 - (t - .75) / .25) ** 1.4)  # it lifts, dry

    def pt(t, off):
        a = th0 + sweep * t
        r = r_at(t) + off
        return cx + r * math.cos(a), cy + r * math.sin(a)

    def stroke(t0, t1, wscale=1.0, bias=0.0, n=220):
        outer, inner = [], []
        for i in range(n + 1):
            t = t0 + (t1 - t0) * i / n
            w = w_at(t) * wscale
            outer.append(pt(t, bias + w * .55))
            inner.append(pt(t, bias - w * .45))
        pts = outer + inner[::-1]
        return "M" + " L".join(f"{x:.2f} {y:.2f}" for x, y in pts) + " Z"

    paths = [stroke(0, 1)]
    # dry-brush strands (kasure) running on past the main stroke
    for bias, t0, t1, ws in ((2.4, .66, .985, .22), (-1.9, .70, .965, .2), (.6, .80, 1.0, .16)):
        paths.append(stroke(t0, t1, ws, bias, 90))
    x0, y0 = pt(0, .4)
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="200" height="200" aria-hidden="true">\n'
        '<!-- Generated by scripts/build_zen_marks.py. A drawn enso, used as a CSS mask. -->\n'
        f'<circle cx="{x0:.2f}" cy="{y0:.2f}" r="3.6" fill="#000"/>\n'
        + "".join(f'<path d="{p}" fill="#000"/>\n' for p in paths)
        + '</svg>\n'
    )


def main() -> None:
    for rel, text in (("img/recursive-logo-seal.svg", build_seal()), ("img/enso.svg", build_enso())):
        (ROOT / rel).write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {rel} ({len(text):,} bytes)")


if __name__ == "__main__":
    main()
